### ISSUE TITLE
Why numeric columns can be string or number?

### ISSUE THREAD

**Issue by OfficialPesonen** [RobinBlomberg/kysely-codegen#109]
I have a column in my database defined as a numeric. Is there any particular reason why the generated type can be a string or number?

I currently have to use Number(valueFromDatabase) to make sure the typescript knows the value is a number.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/109">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/109/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/109/pledge.svg">
</picture>
</a>

**Comment by koskimas** [comment]
Bigint an numberic types can hold values that are larger than the maximum integer the javascript number can express (2^53-1). That's why most db drivers like `pg` return those types as strings by default. 

If you're sure your numbers never exceed that value, you can configure the driver to return numbers. See [this recipe](https://kysely.dev/docs/recipes/data-types).

I don't know how to tell that to kysely-codegen though. There should be a way. @RobinBlomberg can probably elaborate on this.

**Comment by tzezar** [comment]
Has any work been done in this direction?

**Comment by RobinBlomberg** [comment]
This will be released in `kysely-codegen@0.16.0` soon!

**Comment by RobinBlomberg** [comment]
Should be released in [kysely-codegen@0.16.0](https://github.com/RobinBlomberg/kysely-codegen/releases/tag/0.16.0)! 🚀
