### ISSUE TITLE
Type Date is not assignable to type JsonValue

### ISSUE THREAD

**Issue by valentinarau** [RobinBlomberg/kysely-codegen#157]
Hello. I'm using Kysely with PostgresDialect. My table has a column with type `Json`. When I try to insert an object with a Date property  I get this error:
```
Type Date | null is not assignable to type JsonValue | undefined
Type Date is not assignable to type JsonValue | undefined
Type Date is not assignable to type JsonObject
Index signature for type string is missing in type Date
```
I was able to avoid the error either adding `as any` or using `JSON.stringify` before the insert. 

Is there a better solution to this issue?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/157">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/157/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/157/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Hello! JavaScript Date objects are not valid JSON. One could argue that it should be possible to insert/update using any type of value and let the driver convert the values automatically (e.g. `new Date() => "2024-08-14T08:04:58.713Z"`), but that makes Kysely less type-safe compared to having to manually convert to JSON-compatible values.

I would advise you to use `new Date().toISOString()` to make it clear in the code that you're inserting a string instead of a JavaScript Date.
