### ISSUE TITLE
Keep column order

### ISSUE THREAD

**Issue by wirekang** [RobinBlomberg/kysely-codegen#48]
It seems like kysely-codegen sort columns by alphabetically. Why? We have more then 50 columns, and the order is important for readability. Please consider to keep order from `INFORMATION_SCHEMA`.

**Comment by wirekang** [comment]
It seems like this line is the cause of problem. https://github.com/koskimas/kysely/blob/23f004d4ebf55352b6d024b3702843dee6b41bb7/src/dialect/mysql/mysql-introspector.ts#L48

**Comment by wirekang** [comment]
I found an issue https://github.com/koskimas/kysely/issues/146

**Comment by RobinBlomberg** [comment]
Well found!

However, `kysely-codegen` *also* includes code that sorts the tables and columns (and enums I believe) alphabetically. Why? Two reasons:
1. This makes the internal tests consistent—they won't fail due to insertion order or upserts, as long as the data is the same
2. The best default for readability (if you don't have your own specific readability rules) is to order them alphabetically

With that said, it may be a good idea to keep the sorting opt-in or opt-out, so this may be reopened in the future.

**Comment by wirekang** [comment]
Note that `orderBy('column_name')` and `orderBy('ordinal_position')` are both consistent, so tests will never failed as long as the data is the same.

**Comment by RobinBlomberg** [comment]
Of course, if the ordering is part of the tests, they will never fail. My gripe was that the tests kept failing as I were writing and changing them, but as long as the ordering is stable, I guess this may not be a problem.

Regardless, I have not considered column order to matter by design, so I have not taken it into account, but since others may find importance in column order, I should probably make this configurable.

**Comment by aantia** [comment]
@RobinBlomberg Could you re-open this issue? Wirekang closed it after he fixed the upstream issue, but as you said `kysely-codegen` also sorts the values, and in your last comment you indicated that you might implement this as a config setting in future. Or is there another issue for this that I missed?
I would find the output types much more readable if they matched the actual order of the columns, since that's what I spend most of my time looking at.
